.PHONY: pre-commit
pre-commit: version analyze format build

.PHONY: analyze
analyze: version
	flutter analyze

.PHONY: format
format:
	dart format lib

.PHONY: version
version:
	@echo "Generating version from git tags..."
	@VERSION=$$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-unknown"); \
	echo "// This file is auto-generated. Do not edit manually." > lib/version.dart; \
	echo "// Generated by: make version" >> lib/version.dart; \
	echo "const String appVersion = '$$VERSION';" >> lib/version.dart; \
	echo "Generated version: $$VERSION"

.PHONY: build
build: version
	flutter build web --wasm

API_BASE_URL ?= http://localhost:5000

.PHONY: dev-ui-web
dev-ui-web: version
	@echo "Starting Flutter web dev server..."
	@echo "API Base URL: $(API_BASE_URL)"
	flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
