[tool.poetry]
name = "puma-guard"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorflow = "^2.16.1"

[tool.poetry.group.dev.dependencies]
pynblint = "^0.1.5"

[tool.poetry.scripts]
puma-guard = 'puma_guard.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
