[tool.poetry]
name = "pumaguard"
version = "0.0.0"
description = ""
authors = ["Nicolas Bock <nicolasbock@gmail.com>"]
readme = "README.md"
homepage = "http://pumaguard.rtfd.io/"
repository = "https://github.com/PEEC-Nature-Youth-Group/PumaGuard"

[tool.poetry.dependencies]
python = "^3.10"
tensorflow = "^2.15.0"
flask = "^3.0.3"
pillow = "^10.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pylint = "^3.2.6"
bashate = "^2.1.1"
pynblint = "^0.1.6"
mypy = "^1.11.2"
matplotlib = "^3.9.2"
ipykernel = "^6.29.5"

[tool.poetry.scripts]
pick-files = 'scripts.pick_files:main'
pumaguard-server = 'pumaguard.cmd.server:main'
pumaguard-trailcam = 'pumaguard.cmd.trailcam:main'
pumaguard-output = 'pumaguard.cmd.output:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
