[tool.poetry]
name = "pumaguard"
version = "0.0.0"
description = ""
authors = ["Nicolas Bock <nicolasbock@gmail.com>"]
readme = "README.md"
homepage = "http://pumaguard.rtfd.io/"
repository = "https://github.com/PEEC-Nature-Youth-Group/PumaGuard"

[tool.poetry.dependencies]
flask = "^3.0.3"
pillow = "^10.4.0"
python = ">=3.10,<3.12"
tensorflow = "2.17.1"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^24.10.0", markers = 'platform_system != "Windows"' }
bashate = "^2.1.1"
ipykernel = "^6.29.5"
matplotlib = "^3.9.2"
mypy = "^1.11.2"
pylint = "^3.2.6"
pynblint = "^0.1.6"
pytest = "^8.2.2"

[tool.poetry.scripts]
pick-files = 'scripts.pick_files:main'
pumaguard-classify = 'pumaguard.classify:main'
pumaguard-output = 'pumaguard.output:main'
pumaguard-server = 'pumaguard.server:main'
pumaguard-trailcam = 'pumaguard.trailcam:main'
pumaguard-train = 'pumaguard.train:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
