[tool.poetry]
name = "pumaguard"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorflow = "^2.16.1"
flask = "^3.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pylint = "^3.2.6"
bashate = "^2.1.1"
pynblint = "^0.1.6"

[tool.poetry.scripts]
pick-files = 'scripts.pick_files:main'
pumaguard-server = 'pumaguard.cmd.server:main'
pumaguard-trailcam = 'pumaguard.cmd.trailcam:main'
pumaguard-output = 'pumaguard.cmd.output:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
