name: "Clean Runner"
description: "Clean runner by removing unneeded packages"

runs:
  using: "composite"
  steps:
    - name: Get largest installed packages
      run: |
        set +o pipefail
        dpkg-query --show --showformat='${Package;-50}\t${Installed-Size}\n' > packages
        sort --human-numeric-sort --key 2 --reverse packages packages > packages-sorted
        head --lines 20 packages-sorted
      shell: bash
    - name: Remove unnecessary packages on amd64
      run: |
        sudo apt-get remove --auto-remove --purge \
          azure-cli \
          microsoft-edge-stable \
          google-cloud-cli \
          google-chrome-stable \
          \*temurin\* \
          \*llvm\* \
          powershell \
          \*dotnet\* \
          firefox \
          \*jdk\* \
          \*g++\* \
          \*mysql\*
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      shell: bash
    - name: Clean up /usr/local
      run: |
        sudo rm -rf /usr/local/{julia*,aws*}
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/{chromium,powershell}
      shell: bash
    - name: Get largest installed packages
      run: |
        set +o pipefail
        dpkg-query --show --showformat='${Package;-50}\t${Installed-Size}\n' | \
          sort --human-numeric-sort --key 2 --reverse | \
          head --lines 20
      shell: bash
    - name: Get installed snaps
      run: snap list
      shell: bash
