name: pumaguard
base: core24
adopt-info: pumaguard
grade: devel
confinement: devmode

summary: PumaGuard is a machine-learning based Puma mitigation solution
description: |
  More to come...

apps:
  pumaguard-server:
    command: bin/pumaguard-server
  pumaguard-trailcam:
    command: bin/pumaguard-trailcam
  pumaguard-output:
    command: bin/pumaguard-output

parts:
  pumaguard:
    plugin: python
    source: .
    build-packages:
      - git
    override-build: |
      craftctl set version="$(git describe --tags)"
      craftctl default
