name: pumaguard
base: core22 # We need Python <= 3.10
adopt-info: pumaguard
grade: stable
confinement: strict

summary: PumaGuard is a machine-learning based Puma mitigation solution
description: |
  The goal of this project is to accurately classify images based on the
  presence of mountain lions. This can have applications in wildlife
  monitoring, research, and conservation efforts. The model is trained on a
  labeled dataset and validated using a separate set of images.

apps:
  pumaguard-server:
    command: bin/pumaguard-server
  pumaguard-classify:
    command: bin/pumaguard-classify
    completer: bin/classify-bash-completions.sh
  pumaguard-train:
    command: bin/pumaguard-train

parts:
  pumaguard:
    plugin: python
    source: .
    build-packages:
      - git
    override-build: |
      craftctl set version="$(git describe --tags)"
      craftctl default
      cp --recursive models ${CRAFT_PART_INSTALL}/models
      install --mode 0755 scripts/classify-bash-completions.sh ${CRAFT_PART_INSTALL}/bin/classify-bash-completions.sh
