name: Build and Test Webpage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-webpage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r docs/source/requirements.txt

      - name: Build webpage
        run: make -C docs html

      - name: Test webpage
        run: sphinx-build -b linkcheck ./docs/source ./docs/build
