name: Add Issues and Pull Requests to Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/PEEC-Nature-Youth-Group/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
