name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
      - name: Build package
        run: |
          poetry build

  build-snap:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Build Snap package
        run: |
          snapcraft
      - name: Save Snap package
        uses: actions/upload-artifact@v2
        with:
          name: snap-package
          path: ./*.snap
