name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  lint-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install --requirement requirements.txt --requirement test-requirements.txt
      - name: Lint source
        run: pynblint notebooks

  build-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
      - name: Build package
        run: |
          poetry build

  build-snap:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: snap
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snap.outputs.snap }}
