name: Test Python notebooks and sources

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: "3.10"

jobs:
  lint-python-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install --requirement requirements.txt --requirement test-requirements.txt
      - name: Lint Python Notebooks
        run: pynblint notebooks

  lint-python-sources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint Python Sources
        run: poetry run pylint --verbose --rcfile=pylintrc puma_guard tests scripts

  build-python:
    runs-on: ubuntu-latest
    needs: [lint-python-notebooks, lint-python-sources]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest
      - name: Build package
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*

  build-snap:
    runs-on: ubuntu-latest
    needs: [lint-python-notebooks, lint-python-sources]

    steps:
      - name: Check container free disk space
        run: df --human-readable /
      - name: Remove unecessary packages
        run: |
          sudo apt remove --auto-remove --purge \
            azure-cli \
            \*dotnet\* \
            google-chrome-stable \
            google-cloud-cli \
            \*jdk\* \
            microsoft-edge-stable \
            \*mono\* \
            \*mysql\* \
            powershell \
            r-base\*
      - name: Remove unecessary snaps
        run: |
          snap list \
            | awk '{print $1}' \
            | grep -E '(gnome|firefox|gtk)' \
            | xargs --verbose sudo snap remove --purge
      - name: Check container free disk space again
        run: df --human-readable /
      - name: Get largest installed packages
        run: |
          #!/bin/bash
          set -e -u -x
          apt list --installed \
            | grep -v Listing \
            | awk -F / '{print $1}' \
            | xargs apt-cache --no-all-versions show \
            | awk 'BEGIN{ size = 0; package = "" } /^Installed-Size:/{size = $2 } /^Package:/{package = $2} //{ if (size > 0 && package != "") { print size, package; size = 0; package = "" }}' \
            | sort --reverse --numeric-sort \
            | head --lines 30
      - name: Get installed snaps
        run: snap list
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: snap
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snap.outputs.snap }}

  release:
    runs-on: ubuntu-latest
    needs: [build-python, build-snap]
    permissions: write-all

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: snap
      - uses: actions/download-artifact@v4
        with:
          name: python-package
      - run: |
          #!/bin/bash
          set -e -u -x
          ls -lh
          RELEASE_ID=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{ "tag_name": "${{ github.ref_name }}", "name": "Release ${{ github.ref_name }}", "generate_release_notes": true }' \
            | jq --raw-output '.id')
          for snap in *.snap; do
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_CONTEXT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=${snap}" \
              --data-binary "@${snap}"
          done
        if: ${{ github.ref_type == 'tag' }}
