name: Create Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          #!/bin/bash

          set -e -u -x

          echo ${GITHUB_CONTEXT}
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/nicolasbock/extreme-lion-challenge/releases \
            -d '{ \
                  "tag_name": "${{ github.action_ref_name }}", \
                  "target_commitish": "main", \
                  "name": "${{ github.action_ref_name }}", \
                  "body": "Release ${{ github.action_ref_name }}", \
                  "draft": false, \
                  "prerelease":false, \
                  "generate_release_notes": true \
                }'
