# PumaGuard settings
alpha: 0.0001
base-data-directory: ../data
batch-size: 16
color-mode: rgb
epochs: 300
image-dimensions:
- 512
- 512
lion-directories:
- lion
- cougar
model-function: pretrained
model-version: pre-trained
no-lion-directories:
- no_lion
- nocougar
notebook: 6
with-augmentation: false
