# PumaGuard settings
alpha: 1.0e-05
base-data-directory: ../data
batch-size: 16
color-mode: rgb
epochs: 300
image-dimensions:
- 128
- 128
lion-directories:
- lion
model-function: pretrained
model-version: pre-trained
no-lion-directories:
- no_lion
notebook: 5
with-augmentation: false
