# PumaGuard settings
alpha: 1.0e-05
base-data-directory: ../data
batch-size: 16
color-mode: rgb
epochs: 300
image-dimensions:
- 128
- 128
lion-directories:
- lion_1
model-function: pretrained
model-version: pre-trained
no-lion-directories:
- no_lion_1
notebook: 4
with-augmentation: false
