# PumaGuard settings
alpha: 1.0e-05
base-data-directory: /workspaces/PumaGuard/pumaguard/../data
batch-size: 16
color-mode: rgb
epochs: 1
image-dimensions:
- 128
- 128
lion-directories:
- lion
model-function: pre_trained_model
model-version: pre-trained
no-lion-directories:
- no_lion
notebook: 5
with-augmentation: false
