alpha: 1.0e-05
base-data-directory: /workspaces/PumaGuard/pumaguard/../data
batch-size: 16
color-mode: rgb
epochs: 1
image-dimensions:
- 512
- 512
lion-directories:
- lion
- cougar
model-function: pre_trained_model
model-version: pre-trained
no-lion-directories:
- no_lion
- nocougar
notebook: 6
with-augmentation: false
