# PumaGuard settings
alpha: 1.0e-05
base-data-directory: /workspaces/PumaGuard/pumaguard/../data
batch-size: 32
color-mode: grayscale
epochs: 1
image-dimensions:
- 256
- 256
lion-directories:
- lion
model-function: light_model
model-version: light
no-lion-directories:
- no_lion
notebook: 2
with-augmentation: false
