alpha: 1.0e-05
base-data-directory: /workspaces/PumaGuard/pumaguard/../data
batch-size: 16
color-mode: grayscale
epochs: 1
image-dimensions:
- 128
- 128
lion-directories:
- lion
model-function: light_model
model-version: light
no-lion-directories:
- no_lion
notebook: 1
with-augmentation: false
